### PR TITLE
add documentation, minor bug fixes and enhancement of balance sheet

### LINKED ISSUE #41: enhance Balance Sheet

### PR DESCRIPTION
**Pull request by ChrisLangton**
fixes #41

### CODE REVIEW

File: src/main/java/cooper/ui/Ui.java [hunk 1]
```diff
@@ -176,9 +176,18 @@ private static void show(String printMessage) {
...
         show("This is the company's current Balance Sheet:");
+        int balance = 0;
         for (int i = 0; i < balanceSheet.size(); i++) {
-            show(i + 1 + ". " + balanceSheet.get(i));
+            if (balanceSheet.get(i) >= 0) {
+                show(i + 1 + ". inflow of: "+ balanceSheet.get(i));
+                balance += balanceSheet.get(i);
+            }
+            else {
+                show(i + 1 + ". outflow of: "+ balanceSheet.get(i));
```
Comment (theeugenechong) [inline src/main/java/cooper/ui/Ui.java:186]: Add a space between operand and '+' operator
