### PR TITLE
Fix bug for hashmap value type and add exception to catch duplicated names in same availability timeslot

### LINKED ISSUE #24: Fix Hashmap value type to take in an array of strings instead of a string

### PR DESCRIPTION
**Pull request by fansxx**
Changed hashmap value type from string to arraylist.
Fix #24

### CODE REVIEW

File: src/main/java/cooper/meetings/MeetingManager.java [hunk 1]
```diff
@@ -1,21 +1,31 @@
...
+            meetings.get(time).add(name);
+        } else {
+            throw new DuplicateUsernameError();
+        }
     }
 
     public static void printAvailabilities() {
         Ui.printMeetingTableHeader();
         for (String key: meetings.keySet()) {
             Ui.showText(key + " | " + meetings.get(key));
```
Comment (theeugenechong) [inline src/main/java/cooper/meetings/MeetingManager.java:28]: Do you think we can make a method in `Ui` to print out the `ArrayList` of names according to a certain format? (cause `meetings.get(key)` returns an `ArrayList` right?). 
If i'm not wrong, printing it now will just call the `toString()` method for `ArrayList`s.
